name: LaTeX Build

on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

        # The LaTeX document expects 'git-rev.info' that it embeds
        # in the document so it can traced back to a commit
      - name: Generate LaTeX git-info
        working-directory: latex
        run: git rev-parse --short HEAD > git-rev.info

      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          working_directory: latex/
          root_file: cv.tex

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: pdf
          path: latex/cv.pdf