name: LaTeX Build

on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          working_directory: latex/
          root_file: cv.tex

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: pdf
          path: latex/cv.pdf