name: LaTeX Build

on:
  pull_request:
    branches: [ main ]
    paths: [ 'latex/**' ]
  push:
    branches: [ main ]
    paths: [ 'latex/**' ]

  # Allows you to run this workflow manually
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

        # The LaTeX document expects 'git-rev.info' that it embeds
        # in the document so it can traced back to a commit
      - name: Generate LaTeX git-info
        working-directory: latex
        run: git rev-parse --short HEAD > git-rev.info

      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          working_directory: latex/
          root_file: cv.tex

        # Artifact for 'previewing'
      - name: Upload Artifact (Preview)
        uses: actions/upload-artifact@v2
        with:
          name: pdf
          path: latex/cv.pdf

        # Artifact for GitHub Pages
      - name: Upload Artifact (GitHub Pages)
        uses: actions/upload-pages-artifact@v1
        with:
          # Expects a directory
          path: latex/

  publish:
    if: github.event_name == 'push'
    needs: [ build ]
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1